[package]
name = "sail-model"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    # Rust libraries
    "sail_prelude",

    # Generated architectures
    "rust_arch/mret"
]
