//! A set of pre-defined core configurations.
//!
//! The configuration defines which RISC-V extensions are available, as well as some other
//! parameters such as the number and granularity of PMP registers implemented by the core.
//!
//! PRs to contribute new configurations for popular cores are welcome.

use crate::raw;

/// A configuration with all extensions disabled.
pub const MINIMAL: raw::SailConfig = raw::SailConfig {
    extensions: raw::SailConfigExtensions {
        A: raw::SailConfigA { supported: false },
        B: raw::SailConfigB { supported: false },
        FD: raw::SailConfigFD { supported: false },
        M: raw::SailConfigM { supported: false },
        S: raw::SailConfigS { supported: false },
        Smcntrpmf: raw::SailConfigSmcntrpmf { supported: false },
        Sscofpmf: raw::SailConfigSscofpmf { supported: false },
        Sstc: raw::SailConfigSstc { supported: false },
        Sv32: raw::SailConfigSv32 { supported: false },
        Sv39: raw::SailConfigSv39 { supported: false },
        Sv48: raw::SailConfigSv48 { supported: false },
        Sv57: raw::SailConfigSv57 { supported: false },
        Svbare: raw::SailConfigSvbare { supported: false },
        Svinval: raw::SailConfigSvinval { supported: false },
        U: raw::SailConfigU { supported: false },
        V: raw::SailConfigV { supported: false },
        Zaamo: raw::SailConfigZaamo { supported: false },
        Zabha: raw::SailConfigZabha { supported: false },
        Zalrsc: raw::SailConfigZalrsc { supported: false },
        Zba: raw::SailConfigZba { supported: false },
        Zbb: raw::SailConfigZbb { supported: false },
        Zbc: raw::SailConfigZbc { supported: false },
        Zbkb: raw::SailConfigZbkb { supported: false },
        Zbkc: raw::SailConfigZbkc { supported: false },
        Zbkx: raw::SailConfigZbkx { supported: false },
        Zbs: raw::SailConfigZbs { supported: false },
        Zca: raw::SailConfigZca { supported: false },
        Zcb: raw::SailConfigZcb { supported: false },
        Zcd: raw::SailConfigZcd { supported: false },
        Zcf: raw::SailConfigZcf { supported: false },
        Zcmop: raw::SailConfigZcmop { supported: false },
        Zfa: raw::SailConfigZfa { supported: false },
        Zfh: raw::SailConfigZfh { supported: false },
        Zfhmin: raw::SailConfigZfhmin { supported: false },
        Zfinx: raw::SailConfigZfinx { supported: false },
        Zhinx: raw::SailConfigZhinx { supported: false },
        Zicbom: raw::SailConfigZicbom { supported: false },
        Zicboz: raw::SailConfigZicboz { supported: false },
        Zicntr: raw::SailConfigZicntr { supported: false },
        Zicond: raw::SailConfigZicond { supported: false },
        Zifencei: raw::SailConfigZifencei { supported: false },
        Zihpm: raw::SailConfigZihpm { supported: false },
        Zimop: raw::SailConfigZimop { supported: false },
        Zknd: raw::SailConfigZknd { supported: false },
        Zkne: raw::SailConfigZkne { supported: false },
        Zknh: raw::SailConfigZknh { supported: false },
        Zkr: raw::SailConfigZkr { supported: false },
        Zksed: raw::SailConfigZksed { supported: false },
        Zksh: raw::SailConfigZksh { supported: false },
        Zmmul: raw::SailConfigZmmul { supported: false },
        Zvbb: raw::SailConfigZvbb { supported: false },
        Zvbc: raw::SailConfigZvbc { supported: false },
        Zvkb: raw::SailConfigZvkb { supported: false },
        Zvknha: raw::SailConfigZvknha { supported: false },
        Zvknhb: raw::SailConfigZvknhb { supported: false },
        Zvksh: raw::SailConfigZvksh { supported: false },
    },
    memory: raw::SailConfigMemory {
        pmp: raw::SailConfigPmp {
            grain: 0,
        },
    },
};

/// The SiFive U74 core configuration.
pub const U74: raw::SailConfig = raw::SailConfig {
    extensions: raw::SailConfigExtensions {
        A: raw::SailConfigA { supported: true },
        B: raw::SailConfigB { supported: true },
        FD: raw::SailConfigFD { supported: true },
        M: raw::SailConfigM { supported: true },
        S: raw::SailConfigS { supported: true },
        Smcntrpmf: raw::SailConfigSmcntrpmf { supported: false },
        Sscofpmf: raw::SailConfigSscofpmf { supported: false },
        Sstc: raw::SailConfigSstc { supported: false },
        Sv32: raw::SailConfigSv32 { supported: false },
        Sv39: raw::SailConfigSv39 { supported: true },
        Sv48: raw::SailConfigSv48 { supported: false },
        Sv57: raw::SailConfigSv57 { supported: false },
        Svbare: raw::SailConfigSvbare { supported: false },
        Svinval: raw::SailConfigSvinval { supported: false },
        U: raw::SailConfigU { supported: true },
        V: raw::SailConfigV { supported: false },
        Zaamo: raw::SailConfigZaamo { supported: false },
        Zabha: raw::SailConfigZabha { supported: false },
        Zalrsc: raw::SailConfigZalrsc { supported: false },
        Zba: raw::SailConfigZba { supported: true },
        Zbb: raw::SailConfigZbb { supported: true },
        Zbc: raw::SailConfigZbc { supported: false },
        Zbkb: raw::SailConfigZbkb { supported: false },
        Zbkc: raw::SailConfigZbkc { supported: false },
        Zbkx: raw::SailConfigZbkx { supported: false },
        Zbs: raw::SailConfigZbs { supported: false },
        Zca: raw::SailConfigZca { supported: false },
        Zcb: raw::SailConfigZcb { supported: false },
        Zcd: raw::SailConfigZcd { supported: false },
        Zcf: raw::SailConfigZcf { supported: false },
        Zcmop: raw::SailConfigZcmop { supported: false },
        Zfa: raw::SailConfigZfa { supported: false },
        Zfh: raw::SailConfigZfh { supported: false },
        Zfhmin: raw::SailConfigZfhmin { supported: false },
        Zfinx: raw::SailConfigZfinx { supported: false },
        Zhinx: raw::SailConfigZhinx { supported: false },
        Zicbom: raw::SailConfigZicbom { supported: false },
        Zicboz: raw::SailConfigZicboz { supported: false },
        Zicntr: raw::SailConfigZicntr { supported: false },
        Zicond: raw::SailConfigZicond { supported: false },
        Zifencei: raw::SailConfigZifencei { supported: false },
        Zihpm: raw::SailConfigZihpm { supported: false },
        Zimop: raw::SailConfigZimop { supported: false },
        Zknd: raw::SailConfigZknd { supported: false },
        Zkne: raw::SailConfigZkne { supported: false },
        Zknh: raw::SailConfigZknh { supported: false },
        Zkr: raw::SailConfigZkr { supported: false },
        Zksed: raw::SailConfigZksed { supported: false },
        Zksh: raw::SailConfigZksh { supported: false },
        Zmmul: raw::SailConfigZmmul { supported: false },
        Zvbb: raw::SailConfigZvbb { supported: false },
        Zvbc: raw::SailConfigZvbc { supported: false },
        Zvkb: raw::SailConfigZvkb { supported: false },
        Zvknha: raw::SailConfigZvknha { supported: false },
        Zvknhb: raw::SailConfigZvknhb { supported: false },
        Zvksh: raw::SailConfigZvksh { supported: false },
    },
    memory: raw::SailConfigMemory {
        pmp: raw::SailConfigPmp {
            grain: 10,
        },
    },
};
